:+1: replace/add screenshots of axe DevTools
freee/a11y-guidelines pull request #99
Opened 2023-08-16 07:53 UTC by ymrl

SettingsでBest PracticesをONにするところのスクリーンショットを追加。

また、axe DevToolsのUIが変更されていたため、スクリーンショットを差し替えたり、説明を変更したりした。

2023-08-21 02:27 UTC, ma10 requested changes

2023-08-21 02:27 UTC, ma10 commented on source/explanations/axe.rst
> +   :alt: Best Practicesの項目のEnableをチェックしているスクリーンショット
```suggestion
   .. image:: /img/axe-settings.png
      :alt: OptionsからSettingsを開こうとしているスクリーンショット

2. "Best Practices" で "Enable" をチェック

   .. image:: /img/axe-settings-best-practices.png
      :alt: Best Practicesの項目のEnableをチェックしているスクリーンショット
```

2023-08-21 02:27 UTC, ma10 commented on source/explanations/axe.rst
> +ここで、axe DevTools内のUser Impact（当ガイドライン内での「重篤度」などの定義とは別のものです）や、「Best Practices」などを使ってリストをフィルタすることができます。
```suggestion
ここで、axe DevTools内のUser Impact（当ガイドライン内での「重篤度」などの定義とは別のものです）や、「Best Practices」などを使ってリストをフィルターすることができます。
```

2023-08-21 02:30 UTC, ma10 commented on source/explanations/axe.rst
> +   :alt: Best Practicesの項目のEnableをチェックしているスクリーンショット
これでimgが直前のliに入ります。

2023-08-21 08:17 UTC, ymrl commented on source/explanations/axe.rst
> +   :alt: Best Practicesの項目のEnableをチェックしているスクリーンショット
ナルホド

2023-08-22 00:56 UTC, ma10 approved these changes
LGTM

2023-08-31 02:37 UTC, merged